version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      linter:
        applies-to: version-updates
        patterns:
        - "@typescript-eslint/*"
        - "eslint-*"
        - "@tjsr/eslint-config"
        target-branch: "dependabot/eslint"
      mui:
        applies-to: version-updates
        patterns:
        - "@mui/*"
        target-branch: "dependabot/mui"
      react:
        applies-to: version-updates
        patterns:
        - "@types/react"
        - "@types/react-dom"
        - "react"
        - "react-dom"
        target-branch: "dependabot/react"

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
