version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: '@types/node'
        update-types: ["version-update:semver-major"]
    groups:
      linter:
        applies-to: version-updates
        patterns:
        - "@typescript-eslint/*"
        - "eslint-*"
        - "@tjsr/eslint-config"
      mui:
        applies-to: version-updates
        patterns:
        - "@mui/*"
      react:
        applies-to: version-updates
        patterns:
        - "@types/react"
        - "@types/react-dom"
        - "react"
        - "react-dom"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
