#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: atlassian/default-image:3
options:
  docker: true

definitions:
  services:
    docker:
      image: tjsrowe/bb-dind-aws:latest
      variables:
         DOCKER_OPTS: "--insecure-registry=172.29.0.214:5000"

pipelines:
  default:
    - step:
        name: Create image cache
        runs-on:
        - 'self.hosted'
        - 'linux'
        script:
        - npm install
        - npm run download -- $IMAGES_CACHE_DIR
        caches:
          - docker
          - images
    - step:
        name: Build React project
        runs-on:
        - 'self.hosted'
        - 'linux'
        script:
        - npm install
        - npm test
        - mkdir public/imgs
        - cp -Rf $IMAGES_CACHE_DIR/* public/imgs || true
        - npm run build
        caches:
          - docker
          - images

definitions:
  caches:
    images: $IMAGES_CACHE_DIR
